from __future__ import annotations

import uuid
from typing import Literal
from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field


class AISummaryBase(BaseModel):
    strengths: list[str] = Field(..., description="Top strengths of the candidate matching the job.")
    weaknesses: list[str] = Field(..., description="Missing skills or weaknesses regarding the job.")
    recommendation: Literal["Highly Recommended", "Recommended", "Consider", "Rejected"] = Field(..., description="Recommendation status")
    summary_text: str = Field(..., description="A 2-3 sentence professional summary of the candidate's fit.")
    is_fallback: bool = Field(default=False, description="Indicates if this summary was generated by the fallback system.")


class AISummaryCreate(AISummaryBase):
    candidate_id: uuid.UUID
    job_id: uuid.UUID


class AISummaryResponse(AISummaryBase):
    id: uuid.UUID
    candidate_id: uuid.UUID
    job_id: uuid.UUID
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)
