from __future__ import annotations

import uuid
from typing import Literal
from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field


class AISummaryBase(BaseModel):
    strengths: list[str] = Field(..., description="Top strengths of the candidate matching the job.")
    weaknesses: list[str] = Field(..., description="Missing skills or weaknesses regarding the job.")
    recommendation: Literal["Highly Recommended", "Recommended", "Consider", "Rejected"] = Field(..., description="Recommendation status")
    summary_text: str = Field(..., description="A 2-3 sentence professional summary of the candidate's fit.")
    is_fallback: bool = Field(default=False, description="Indicates if this summary was generated by the fallback system.")


class AISummaryCreate(AISummaryBase):
    candidate_id: uuid.UUID
    job_id: uuid.UUID


class AISummaryResponse(AISummaryBase):
    id: uuid.UUID
    candidate_id: uuid.UUID
    job_id: uuid.UUID
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class InterviewQuestion(BaseModel):
    question: str = Field(..., description="The interview question text.")
    category: str = Field(..., description="The category of the question (e.g., Technical, Behavioral).")
    difficulty: Literal["Easy", "Medium", "Hard"] = Field(..., description="Difficulty level.")
    expected_skill: str = Field(..., description="The skill this question assesses.")


class InterviewQuestionResponse(BaseModel):
    questions: list[InterviewQuestion] = Field(..., description="List of generated interview questions.")
    is_fallback: bool = Field(default=False, description="Indicates if these questions were generated by the fallback system.")


class AIGenerateRequest(BaseModel):
    candidate_id: uuid.UUID = Field(..., description="The UUID of the candidate.")
    job_id: uuid.UUID = Field(..., description="The UUID of the job.")


class AIGenerateResponse(BaseModel):
    job_id: str = Field(..., description="The async job ID for tracking.")
    status: str = Field(..., description="The status of the job (e.g., QUEUED).")
    status_url: str = Field(..., description="The URL to poll for job status.")


class SkillGapResponse(BaseModel):
    matching_skills: list[str] = Field(..., description="Skills present in both candidate and job.")
    missing_skills: list[str] = Field(..., description="Skills required by the job but missing from the candidate.")
    match_percentage: float = Field(..., description="Percentage of required skills the candidate possesses.")
